[app]
name=Zc-Manager
port=8080		#服务器端口号
#资料路径
win_profile=E:/zc-manager-system/profile 
linux_profile=/opt/zc-manager-system/profile

[mysql]
host=127.0.0.1
port=3306
user=root
password=mysql1228.
db=zc-manager
max-size=5

[redis]
host=127.0.0.1
port=6379
password=123456
db=0
max-size=5
idle-timeout=300	#5min
life-timeout=600	#10min
wait-timeout=10		#10s
