#运行mysql docker容器
docker run -d  -p 3306:3306 \
  --name mysql-8.4 \
  -e MYSQL_ROOT_PASSWORD=123456 \
  -e MYSQL_DATABASE=hdy_manager_system \
  -v mysql-data:/var/lib/mysql \
  -v /etc/mysql/conf.d:/etc/mysql/conf.d \
  mysql:8.4       

#运行redis docker容器
## 创建目录
sudo mkdir -p /opt/redis/conf
sudo mkdir -p /opt/redis/data

## 创建文件
sudo touch /opt/redis/conf/redis.conf

# Docker 创建 Redis 容器命令
sudo docker run \
--restart=always \
--log-opt max-size=100m \
--log-opt max-file=2 \
-p 6379:6379 \
--name redis \
-v /opt/redis/conf/redis.conf:/etc/redis/redis.conf  \
-v /opt/redis/data:/data \
-d redis:latest redis-server /etc/redis/redis.conf \
--appendonly yes \
--requirepass 123456 
